version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      all-dependencies:
        patterns: ["*"]
    open-pull-requests-limit: 3
    commit-message:
      prefix: "chore(deps)"
